language: "python"
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  global:
    - NOMAD_IP="127.0.0.1"
    - NOMAD_PORT="4646"
  matrix:
    - NOMAD_VERSION="0.3.2"

before_install:
    - "curl -L -o /tmp/${NOMAD_VERSION}_linux_amd64.zip https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_linux_amd64.zip"
    - "unzip /tmp/${NOMAD_VERSION}_linux_amd64.zip"
    - ./nomad agent -dev &

install:
  - pip install -r requirements-dev.txt

script:
  - py.test --cov=nomad --cov-report=term-missing --runxfail tests/

after_success:
  - coveralls